routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    if (auth()->user()) {
        return view("home");
    } else {
        return view("auth.login");
    }
});

Auth::routes();

Route::match(['get', 'post'], '/register', function () {
    return redirect("/login");
})->name("register");

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('/users', 'UserController');
Route::get("/categories/trash", 'CategoryController@trash')->name('categories.trash');
Route::get('/categories/{id}/restore', 'CategoryController@restore')->name('categories.restore');
Route::delete('/categories/{category}/delete-permanent', 'CategoryController@deletePermanent')->name('categories.delete-permanent');
Route::get('/ajax/categories/search', 'CategoryController@ajaxSearch');
Route::resource('/categories', 'CategoryController');
Route::get('/books/trash', 'BookController@trash')->name('books.trash');
Route::post('/books/{book}/restore', 'BookController@restore')->name('books.restore');
Route::delete('/books/{id}/delete-permanent', 'BookController@deletePermanent')->name('books.delete-permanent');
Route::resource('/books', 'BookController');
Route::resource('orders', 'OrderController');

app/Book.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Book extends Model
{
    use SoftDeletes;

    public function categories()
    {
        return $this->belongsToMany('App\Category');
    }

    public function orders()
    {
        return $this->belongsToMany('App\Order');
    }
}

app/Http/Controllers/BookController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;

class BookController extends Controller
{

    public function __construct()
    {
        $this->middleware(function ($request, $next) {
            if (Gate::allows('manage-books')) return $next($request);
            abort(403, 'Anda tidak memiliki cukup hak akses');
        });
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $status = $request->get("status");
        $keyword = $request->get("keyword") ? $request->get("keyword") : '';
        if ($status) {
            $books = \App\Book::with('categories')->where('title', 'LIKE', "%$keyword%")->where('status', strtoupper($status))->paginate(10);
        } else {
            $books = \App\Book::with('categories')->where('title', 'LIKE', "%%$keyword")->paginate(10);
        }
        return view('books.index', compact('books'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view("books.create");
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        // validasi form
        \Validator::make($request->all(), [
            "title" => "required|min:5|max:200",
            "description" => "required|min:20|max:1000",
            "author" => "required|min:3|max:100",
            "publisher" => "required|min:3|max:200",
            "price" => "required|digits_between:0,10",
            "stock" => "required|digits_between:0,10",
            "cover" => "required"
        ])->validate();

        $newBook = new \App\Book;
        $newBook->title = $request->get("title");
        $cover = $request->file("cover");
        if ($cover) {
            $coverPath = $cover->store("book_covers", "public");
            $newBook->cover = $coverPath;
        }
        $newBook->description = $request->get("description");
        $newBook->stock = $request->get("stock");
        $newBook->author = $request->get("author");
        $newBook->publisher = $request->get("publisher");
        $newBook->price = $request->get("price");
        $newBook->status = $request->get("save_action");
        $newBook->slug = \Str::slug($request->get("title"));
        $newBook->created_by = \Auth::user()->id;
        $newBook->save();
        $newBook->categories()->attach($request->get('categories'));
        if ($request->get("save_action") == "PUBLISH") {
            return redirect()->route("books.create")->with("status", "Book Succesfully saved and publsihed");
        } else {
            return redirect()->route("books.create")->with("status", "Book saved as Draft");
        }
    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $book = \App\Book::findOrFail($id);

        return view("books.edit", compact('book'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $book = \App\Book::findOrFail($id);

        // validasi form
        \Validator::make($request->all(), [
            "title" => "required|min:5|max:200",
            "slug" => [
                "required",
                Rule::unique("books")->ignore($book->slug, "slug")
            ],
            "description" => "required|min:20|max:1000",
            "author" => "required|min:3|max:100",
            "publisher" => "required|min:3|max:200",
            "price" => "required|digits_between:0,10",
            "stock" => "required|digits_between:0,10",
        ])->validate();

        $book->title = $request->get("title");
        $book->slug = $request->get("slug");
        $book->description = $request->get("description");
        $book->author = $request->get("author");
        $book->publisher = $request->get("publisher");
        $book->stock = $request->get("stock");
        $book->price = $request->get("price");
        $newCover = $request->file("cover");
        if ($newCover) {
            if ($book->cover && file(storage_path("app/public/" . $book->cover))) {
                \Storage::delete("public/" . $book->cover);
            }
            $newCoverPath = $newCover->store("book_covers", "public");
            $book->cover = $newCoverPath;
        }
        $book->updated_by = \Auth::user()->id;
        $book->status = $request->get("status");
        $book->save();
        $book->categories()->sync($request->get('categories'));
        return redirect()->route("books.index")->with("status", "Book succesfully Updated");
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $book = \App\Book::findOrFail($id);
        $book->delete();
        return redirect()->route("books.index")->with("status", "Book Moved to trash");
    }

    // trash
    public function trash()
    {
        $books = \App\Book::onlyTrashed()->paginate(10);
        return view("books.trash", compact("books"));
    }

    // restore method | created by Muhammad Kuswari
    public function restore($id)
    {
        $book = \App\Book::withTrashed()->findOrFail($id);
        if ($book->trashed()) {
            $book->restore();
            return redirect()->route("books.index")->with("status", "Book succesfully restored");
        } else {
            return redirect()->route("books.index")->with("status", "Book is not in trash");
        }
    }

    // delete permanent method | created by Muhammad Kuswari
    public function deletePermanent($id)
    {
        $book = \App\Book::withTrashed()->findOrFail($id);
        if (!$book->trashed()) {
            return redirect()->route("books.trash")->with("status", "Book is not on trash")->with('status_type', 'alert');
        } else {
            $book->categories()->detach();
            $book->forceDelete();
            return redirect()->route("books.trash")->with("status", "Book Permanenlty deleted");
        }
    }
}

resources/views/books/create.blade.php
@extends('layouts.master')

@section('title')
    Add Book
@endsection

@section('content')
    <div class="row">
        <div class="col-sm-8">
            <div class="card">
                <div class="card-body">
                    @if (session("status"))
                        <div class="alert alert-success">
                            {{ session("status") }}
                        </div>
                    @endif
                    <form action="{{ route("books.store") }}" method="post" enctype="multipart/form-data">
                        @csrf
                        <div class="form-group">
                          <label for="title">Book Title</label>
                          <input type="text" name="title" id="title" class="form-control {{ $errors->first('title') ? 'is-invalid' : '' }}">
                          <span class="invalid-feedback">
                              {{ $errors->first('title') }}
                          </span>
                        </div>
                        <div class="form-group">
                          <label for="cover">Book Cover</label>
                          <input type="file" class="form-control-file {{ $errors->first('cover') ? 'is-invalid' : '' }}" name="cover" id="cover">
                          <span class="invalid-feedback">
                              {{ $errors->first('cover') }}
                          </span>
                        </div>
                        <div class="form-group">
                          <label for="description">Description</label>
                          <textarea class="form-control {{ $errors->first('description') }}" name="description" id="description" rows="3"></textarea>
                          <span class="invalid-feedback">
                              {{ $errors->first('description') }}
                          </span>
                        </div>
                        <div class="form-group">
                            <label for="categories">Categories</label>
                            <select name="categories[]" multiple id="categories" class="form-control"></select>
                        </div>
                        <div class="form-group">
                            <label for="stock">Stock</label>
                            <input type="number" class="form-control {{ $errors->first('stock') ? 'is-invalid' : '' }}" name="stock" id="stock">
                            <span class="invalid-feedback">
                                {{ $errors->first('stock') }}
                            </span>
                        </div>
                        <div class="form-group">
                          <label for="author">Author</label>
                          <input type="text" name="author" id="author" class="form-control {{ $errors->first('author') ? 'is-invalid' : '' }}">
                          <span class="invalid-feedback">
                              {{ $errors->first('author') }}
                          </span>
                        </div>
                        <div class="form-group">
                          <label for="publisher">Publisher</label>
                          <input type="text" name="publisher" id="publisher" class="form-control {{ $errors->first('publisher') ? 'is-invalid' : '' }}">
                          <span class="invalid-feedback">
                              {{ $errors->first('publisher') }}
                          </span>
                        </div>
                        <div class="form-group">
                            <label for="price">Book Price</label>
                            <input type="number" name="price" id="price" class="form-control {{ $errors->first('price') ? 'is-invalid' : '' }}">
                            <span class="invalid-feedback">
                                {{ $errors->first('price') }}
                            </span>
                        </div>
                        <hr>
                        <div class="form-acton">
                            <button name="save_action" class="btn btn-primary" value="PUBLISH">Publish Book</button>
                            <button name="save_action" class="btn btn-warning" value="DRAFT">Save as Draft</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('footer-scripts')

<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />

<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>

<script>
    $('#categories').select2({
    ajax: {
        url: 'http://127.0.0.1:8000/ajax/categories/search',
        processResults: function(data){
        return {
            results: data.map(function(item){return {id: item.id, text: item.name} })
        }
        }
    }
    });
</script>

@endsection

resources/views/books/edit.blade.php
@extends('layouts.master')

@section('title')
    Add Book
@endsection

@section('content')
    <div class="row">
        <div class="col-sm-8">
            <div class="card">
                <div class="card-body">
                    @if (session("status"))
                        <div class="alert alert-success">
                            {{ session("status") }}
                        </div>
                    @endif
                    <form action="{{ route("books.update", [$book->id]) }}" method="post" enctype="multipart/form-data">
                        @csrf
                        <input type="hidden" name="_method" value="PUT">
                        <div class="form-group">
                          <label for="title">Book Title</label>
                          <input type="text" name="title" id="title" class="form-control {{ $errors->first('title') ? 'is-invalid' : '' }}" value="{{ $book->title }}">
                          <span class="invalid-feedback">
                              {{ $errors->first('title') }}
                          </span>
                        </div>
                        <div class="form-group">
                          <label for="cover">Book Cover</label>
                          <br>
                          @if ($book->cover)
                              <img src="{{ asset("storage/".$book->cover) }}" width="500">
                          @endif
                          <input type="file" class="form-control-file {{ $errors->first('cover') ? 'is-invalid' : '' }}" name="cover" id="cover">
                          <small class="text-muted">Kosongka jika tidak ingin merubah</small>
                          <span class="invalid-feedback">
                              {{ $errors->first('cover') }}
                          </span>
                        </div>
                        <div class="form-group">
                          <label for="slug">Slug</label>
                          <input type="text" name="slug" id="slug" class="form-control {{ $errors->first('slug') ? 'is-invalid' : '' }}" value="{{ $book->slug }}">
                          <span class="invalid-feedback">
                              {{ $errors->first('slug') }}
                          </span>
                        </div>
                        <div class="form-group">
                          <label for="description">Description</label>
                          <textarea class="form-control {{ $errors->first('description') ? 'is-invalid' : '' }}" name="description" id="description" rows="3">{{ $book->description }}</textarea>
                          <span class="invalid-feedback">
                              {{ $errors->first('description') }}
                          </span>
                        </div>
                        <div class="form-group">
                            <label for="categories">Categories</label>
                            <select name="categories[]" multiple id="categories" class="form-control"></select>
                        </div>
                        <div class="form-group">
                            <label for="stock">Stock</label>
                            <input type="number" class="form-control {{ $errors->first('stock') ? 'is-invalid' : '' }}" name="stock" id="stock" value="{{ $book->stock }}">
                            <span class="invalid-feedback">
                                {{ $errors->first('stock') }}
                            </span>
                        </div>
                        <div class="form-group">
                          <label for="author">Author</label>
                          <input type="text" name="author" id="author" class="form-control {{ $errors->first('author') }}" value="{{ $book->author }}">
                          <span class="invalid-feedback">
                              {{ $errors->first('author') }}
                          </span>
                        </div>
                        <div class="form-group">
                          <label for="publisher">Publisher</label>
                          <input type="text" name="publisher" id="publisher" class="form-control {{ $errors->first('publisher') ? 'is-invalid' : '' }}" value="{{ $book->publisher }}">
                          <span class="invalid-feedback">
                              {{ $errors->first('publisher') }}
                          </span>
                        </div>
                        <div class="form-group">
                            <label for="price">Book Price</label>
                            <input type="number" name="price" id="price" class="form-control {{ $errors->first('price') ? 'is-invalid' : '' }}" value="{{ $book->price }}">
                            <span class="invalid-feedback">
                                {{ $errors->first('price') }}
                            </span>
                        </div>
                        <div class="form-group">
                            <label for="status">Status</label>
                            <select name="status" id="status" class="form-control">
                                <option value="PUBLISH" {{ $book->status == "PUBLISH" ? "selected" : "" }}>Publish</option>
                                <option value="DRAFT" {{ $book->statuus == "DRAFT" ? "selected" : "" }}>Draft</option>
                            </select>
                        </div>
                        <hr>
                        <div class="form-acton">
                            <button name="save_action" class="btn btn-primary" value="PUBLISH">Update Book</button>
                            <button name="save_action" class="btn btn-warning" value="DRAFT">Save as Draft</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('footer-scripts')

<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />

<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>

<script>
    $('#categories').select2({
    ajax: {
        url: 'http://127.0.0.1:8000/ajax/categories/search',
        processResults: function(data){
        return {
            results: data.map(function(item){return {id: item.id, text: item.name} })
        }
        }
    }
    });

    var categories = {!! $book->categories !!}
    categories.forEach(function(category){
      var option = new Option(category.name, category.id, true, true);
      $('#categories').append(option).trigger('change');
    });

</script>

@endsection

resources/views/books/index.blade.php
@extends('layouts.master')

@section('title')
    List Books
@endsection

@section('content')
<div class="card">
    <div class="card-header">

        <div class="d-sm-flex align-items-center justify-content-between">
        <div class="action-naviation">
            <a href="{{ route("books.create") }}" class="btn btn-primary mr-3">Add new category</a>
            <a href="{{ route("books.index") }}" class="mr-3 {{ Request::get('status') == NULL && Request::path() == 'books' ? 'font-weight-bold text-success' : '' }} ">All Book</a>
            <a href="{{ route("books.index", ['status' => 'publish']) }}" class="mr-3 {{ Request::get('status') == 'publish' ? 'font-weight-bold text-success' : '' }}">Publishhed</a>
            <a href="{{ route("books.index", ['status' => 'draft']) }}" class="mr-3 {{ Request::get('status') == 'draft' ? 'font-weight-bold text-success' : '' }}">Draft</a>
            <a href="{{ route("books.trash") }}" class="mr-3 {{ Request::path() == 'books/trash' ? 'font-weight-bold text-success' : '' }}">Trash</a>
        </div>
        <form action="{{ route("books.index") }}" class="d-sm-inline-block form-inline">
            <div class="form-group">
              <input type="text" class="form-control mr-1" placeholder="Filter title..." name="keyword" value="{{ Request::get("keyword") }}">
              <button type="submit" class="btn btn-primary">Filter Book</button>
            </div>
          </form>
        </div>
    </div>
    <div class="card-body">
            @if (session("status"))
                <div class="alert alert-success" role="alert">
                    {{ session("status") }}
                </div>
            @endif
    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <th>No</th>
                <th>Cover</th>
                <th>Title</th>
                <th>Author</th>
                <th>Status</th>
                <th>Categories</th>
                <th>Stock</th>
                <th>Price</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
        @foreach ($books as $book)
            <tr>
                <td scope="row">{{ $loop->iteration }}</td>
                <td>
                    @if ($book->cover)
                        <img src="{{ asset("storage/".$book->cover) }}" width="100">
                    @endif
                </td>
                <td>{{ $book->title }}</td>
                <td>{{ $book->author }}</td>
                <td>
                    @if ($book->status == "DRAFT")
                        <span class="badge badge-warning">{{ $book->status }}</span>
                    @else
                        <span class="badge badge-success">{{ $book->status }}</span>
                    @endif
                </td>
                <td>
                    <ul class="pl-3">
                        @foreach ($book->categories as $category)
                            <li>{{ $category->name }}</li>
                        @endforeach
                    </ul>
                </td>
                <td>{{ $book->stock }}</td>
                <td>{{ $book->price }}</td>
                <td>
                    <a href="{{ route("books.edit", [$book->id]) }}" class="btn btn-warning btn-sm">Edit</a>
                    <form action="{{ route("books.destroy", [$book->id]) }}" method="post" class="d-inline" onsubmit="return confirm('Move this Book to Trash?')">
                    @csrf
                    <input type="hidden" name="_method" value="DELETE">
                    <button type="submit" class="btn btn-danger btn-sm">Trash</button>
                    </form>
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
    </div>
</div>
<div class="pagination mt-2">
    {{ $books->links() }}
</div>
@endsection

resources/views/books/trash.blade.php
@extends('layouts.master')

@section('title')
    List Books
@endsection

@section('content')
<div class="card">
    <div class="card-header">

        <div class="d-sm-flex align-items-center justify-content-between">
        <div class="action-naviation">
            <a href="{{ route("books.create") }}" class="btn btn-primary mr-3">Add new category</a>
            <a href="{{ route("books.index") }}" class="mr-3 {{ Request::get('status') == NULL && Request::path() == 'books' ? 'font-weight-bold text-success' : '' }} ">All Book</a>
            <a href="{{ route("books.index", ['status' => 'publish']) }}" class="mr-3 {{ Request::get('status') == 'publish' ? 'font-weight-bold text-success' : '' }}">Publishhed</a>
            <a href="{{ route("books.index", ['status' => 'draft']) }}" class="mr-3 {{ Request::get('status') == 'draft' ? 'font-weight-bold text-success' : '' }}">Draft</a>
            <a href="{{ route("books.trash") }}" class="mr-3 {{ Request::path() == 'books/trash' ? 'font-weight-bold text-success' : '' }}">Trash</a>
        </div>
        <form action="{{ route("books.index") }}" class="d-sm-inline-block form-inline">
            <div class="form-group">
              <input type="text" class="form-control mr-1" placeholder="Filter title..." name="keyword" value="{{ Request::get("keyword") }}">
              <button type="submit" class="btn btn-primary">Filter Book</button>
            </div>
          </form>
        </div>
    </div>
    <div class="card-body">
            @if (session("status"))
                <div class="alert alert-success" role="alert">
                    {{ session("status") }}
                </div>
            @endif
    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <th>No</th>
                <th>Cover</th>
                <th>Title</th>
                <th>Author</th>
                <th>Status</th>
                <th>Categories</th>
                <th>Stock</th>
                <th>Price</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
        @foreach ($books as $book)
            <tr>
                <td scope="row">{{ $loop->iteration }}</td>
                <td>
                    @if ($book->cover)
                        <img src="{{ asset("storage/".$book->cover) }}" width="100">
                    @endif
                </td>
                <td>{{ $book->title }}</td>
                <td>{{ $book->author }}</td>
                <td>
                    @if ($book->status == "DRAFT")
                        <span class="badge badge-warning">{{ $book->status }}</span>
                    @else
                        <span class="badge badge-success">{{ $book->status }}</span>
                    @endif
                </td>
                <td>
                    <ul class="pl-3">
                        @foreach ($book->categories as $category)
                            <li>{{ $category->name }}</li>
                        @endforeach
                    </ul>
                </td>
                <td>{{ $book->stock }}</td>
                <td>{{ $book->price }}</td>
                <td>
                    <form action="{{ route("books.restore", [$book->id]) }}" method="post" class="d-inline" onsubmit="return confirm('Restore this book?')">
                        @csrf
                        <button type="submit" class="btn btn-success btn-sm">Restore</button>
                    </form>
                    <form action="{{ route("books.delete-permanent", [$book->id]) }}" method="post" class="d-inline" onsubmit="return confirm('Move this Book to Trash?')">
                        @csrf
                        <input type="hidden" name="_method" value="DELETE">
                        <button type="submit" class="btn btn-danger btn-sm">Delete</button>
                    </form>
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
    </div>
</div>
<div class="pagination mt-2">
    {{ $books->links() }}
</div>
@endsection